### ISSUE TITLE
Jumbled notes after opening settings

### ISSUE THREAD

**Issue by Fmoment1** [PhilKes/NotallyX#100]
### What happened?

Having an issue where opening the settings and returning to notes jumbles up the note order (random notes showing up under pinned notes, etc).

This is also applicable after opening any of the options from the sidebar (labels, deleted, archive).

This is fixed by opening a note and closing it.

### App Version

v6.0

### Android Version

11

**Comment by PhilKes** [comment]
I think this was a minor bug that I already fixed, but the fix is not in `v.6.0`.
I guess we have to wait for `v6.1` release and then check again
