### ISSUE TITLE
Migrate Theme to Material 3

### ISSUE THREAD

**Issue by Sureshgorai25** [PhilKes/NotallyX#104]
It would be great if we get a feature to custom corner radius of a note in the grid/list mode.

**Comment by Sureshgorai25** [comment]
Can you make the corner radius little bit more rounded to match material you design?

**Comment by PhilKes** [comment]
> Can you make the corner radius little bit more rounded to match material you design?

I see, atm the corner radius of the Material `Card` for the notes arent modified it just uses the defaults.
 Currently the app's theme is derived from `Theme.MaterialComponents.DayNight.NoActionBar` which is based on Material 2, so if you want to comply with the most recent Material Design version we would have to change it to `Theme.Material3.DayNight.NoActionBar`. The cards then look like this:
 
<img src="https://github.com/user-attachments/assets/5476dbe9-66f8-483f-8eb3-4ea3052fc3b3" width="400" />

But as you can see e.g. for the Floating Action Buttons this changes a lot of other properties too, so I will have to take a look at the entire app so the theme is consistent and still works as intended.
