### ISSUE TITLE
Sync devices using Syncthing 

### ISSUE THREAD

**Issue by yerc** [PhilKes/NotallyX#109]
**Describe the solution you'd like**
I would like NotallyX to sync between my phone and tablet locally using Syncthing [https://syncthing.net/](url)

**Additional context**
For this to happen an app has to save its data files in a user-accessible folder.  Syncthing will then synchronize the folder in one device (example phone)  with the same app's data files in another device (example tablet).

Thanks for adding features I was hoping Notally had.

**Comment by ippocratis** [comment]
You can sync you backup folder with it.
You can even backup to a WebDAV mount.

Also have in mind that syncthing for android development is stale.

**Comment by PhilKes** [comment]
As you proposed I would consider configuring whether the app uses the apps internal storage or some user-specified folder on the device. That would enable you as @ippocratis said to use syncthing, WebDAV or whatever to sync the files between devices.
What I dont want is to manually add service-specific integrations, since maintaining it would take a lot of effort

**Comment by yerc** [comment]
Thanks @PhilKes for considering to allow user the choice between app internal storage and user-specified folder for my proposal to happen.  I know I can do backups which can be restored elsewhere, but that does not make the devices in sync.  For what it's worth, Syncthing on Android lives on thanks to Syncthing-fork.

**Comment by PhilKes** [comment]
@yerc As far as I can see its not directly possible to move the Database (RoomDatabase) out of the app-specific storage into any user-picked folder. Would it be sufficient if you can choose to either use the app's internal storage or the app's external storage (e.g. `/storage/emulated/0/Android/data/com.philkes.notallyx`)?

**Comment by yerc** [comment]
Thanks @PhilKes.  As the user can access /storage/emulated/0/Android/media/com.philkes.notallyx, moving the Database to this location should make it possible to sync NotallyX between devices through Syncthing.

**Comment by jawsh207** [comment]
Just opened a similar issue, except I am using Syncthing to sync between Android and Debian 12. No note app I've directed at the folder seems to be able to detect anything on the Linux side tho. Any solutions to this? What kind of database is being used by NotallyX to store the notes?

**Comment by ippocratis** [comment]
NotallyX is not a multiplatform note app 

You can use the exported database as is in another note app on a different platform 

Database is an encrypted sqlite

**Comment by jawsh207** [comment]
> NotallyX is not a multiplatform note app
> 
> You cant use the exported database as is in another note app on a different platform
> 
> Database is an encrypted sqlite

I'm aware it isn't multiplatform. That wasn't my question. But I've since learned that this isn't really an issue with NotallyX, it's an issue with note apps on Android general. Or not am issue, depending on how you look at it. In order to do what I need would take a note app that saves each note individually as as a txt file or markdown so I could sync and open under Linux as well. I'm not aware of anything that allows this.

**Comment by ippocratis** [comment]
>  In order to do what I need would take a note app that saves each note individually as as a txt file or markdown so I could sync and open under Linux as well. I'm not aware of anything that allows this. 

You can export your notally not as as plain text,PDF,json,html

**Comment by jawsh207** [comment]
> > In order to do what I need would take a note app that saves each note individually as as a txt file or markdown so I could sync and open under Linux as well. I'm not aware of anything that allows this.
> 
> You can export your notallyx notes as plain text,PDF,json,html

Backing up my notes is not what I'm trying to accomplish. Syncing notes to another platform and bote application is.

**Comment by yerc** [comment]
> > NotallyX is not a multiplatform note app
> > You cant use the exported database as is in another note app on a different platform
> > Database is an encrypted sqlite
> 
> I'm aware it isn't multiplatform. That wasn't my question. But I've since learned that this isn't really an issue with NotallyX, it's an issue with note apps on Android general. Or not am issue, depending on how you look at it. In order to do what I need would take a note app that saves each note individually as as a txt file or markdown so I could sync and open under Linux as well. I'm not aware of anything that allows this.

Was so delighted to see that the "Store Data on External Storage" has been switched on.  Unfortunately syncing my phone to my tablet using Syncthing  didn't work.  Not a NotallyX issue, it's just how Syncthing expects files to be saved individually as do apps I use like KeePassDX and Obsidian, or to use DecSync to  as a bridge as does Tasks.org.  Really appreciate PhilKe's efforts. 

@jawsh207 you might want to have a look Obsidian or Markor for note taking - both saved the notes individually.

**Comment by PhilKes** [comment]
As described in #164, moving to a file-based approach wpuld take a lot of effort, but I will look into it when I find them.

@yerc why does syncing your phone and tablet not work? If you set  "Store data kn External Storage" on both devices and setup "android/media/com.philkes.notallyx" to be synched, it should work. But as of now I havent tested this scenario in full myself, so be sure to backup your notes to another location before
