### ISSUE TITLE
Pinning does not work 

### ISSUE THREAD

**Issue by Depudee** [PhilKes/NotallyX#110]
### What happened?

Notes are pinnend even though they are not been marked as such. 
In this example only "Todo Liste" is pinned. 

![IMG_20241105_081117](https://github.com/user-attachments/assets/5565fbd0-ce8a-4388-8afe-18ccc75b9f8f)

### App Version

6.0

### Android Version

15

**Comment by PhilKes** [comment]
I remember a minor issue with the sorting of the notes not properly propagated to the displayed List, but I fixed that.
Would be good if you could test your notes with the [v6.1-RC3](https://github.com/PhilKes/NotallyX/releases/tag/v6.1-RC3) to make sure its fixed. If you dont want/cant test a pre-release .apk on your device, we'll best just wait until I release the `v6.1`

**Comment by CodeNomadHQ** [comment]
It should be fixed in the latest update, as shown in the image.

<img width="503" alt="Image" src="https://github.com/user-attachments/assets/9c7f0b91-ead2-4fe1-bdda-44d1cefb25e3">

**Comment by PhilKes** [comment]
Will close this for now since it should be fixed, if it re-occurs, feel free to open another issue 😄
