### ISSUE TITLE
NotallyX vs Notally

### ISSUE THREAD

**Issue by rafnov** [PhilKes/NotallyX#135]
What's the relation between those two? I can see very similiar UI but different developer. Anyone made comparison?

Edit:
Sorry for bothering, just found "Features - Notally but eXtended" and descriptive list of them.

But maybe is something more I should know? Just curious ;)

**Comment by PhilKes** [comment]
NotallyX is an independent fork of the original Notally app.
As @ippocratis stated I wanted to make some improvements to the app but the original developer of Notally seemed inactive and not really open to contributions from the community. Therefore I created NotallyX which is based on Notally, with the same GPL 3.0 license, but with the goal of people being able to contribute code as well as feature requests, bug reports etc.

**Comment by rafnov** [comment]
Very nice. Contact with the dev is very important, and most apps devs I use and test lately do react that or another way, but mostly very reliably and explanatory. I appreciate that very much.
I can give an example from the other pole of this continuity, that I experienced and really hate: Waterfox devs never ever reacted. My cases weren't isolated and single ones. Just an example.

Thank you for your work and keep it that way.

**Comment by Joduai** [comment]
While transferring data to new phone I was just about to install notally through fdroid, and notallyX also popped up. 
I was curious if this app had anything in common with said notally.   
I've found the info in readme but wanted to know a bit more about creating new app.  
I'm glad I found this thread with dev explanation, although I was expecting to see "forked from...".

**Comment by ippocratis** [comment]
> I'm glad I found this thread with dev explanation, although I was expecting to see "forked from...".

Its literally stated in the repo header that its notally but extended.

And in the app features the initial notally link is parsed and tat the licence is following the initial notally app.

Not sure what else you need.

Notally x is far from a fork .


https://github.com/PhilKes/NotallyX/issues/20
