### ISSUE TITLE
List notes deleting item even though text is not empty on backspace pressed

### ISSUE THREAD

**Issue by WaterTreee** [PhilKes/NotallyX#142]
Such as title,List notes can't delete words except the first line by pressing the backspace key.

Besides, this application is great, I like it very much, and I look forward to your update.

**Comment by PhilKes** [comment]
I am not sure I understand, can you describe what you mean with "delete words"?

[notallyx_issues_142.webm](https://github.com/user-attachments/assets/3ef18255-bfe8-42bc-8a6c-4007c695d91d)

**Comment by WaterTreee** [comment]
> I am not sure I understand, can you describe what you mean with "delete words"?
> 
> [notallyx_issues_142.webm](https://github.com/user-attachments/assets/3ef18255-bfe8-42bc-8a6c-4007c695d91d)
> 


Like this：

https://github.com/user-attachments/assets/ffba3eec-e2f9-4f48-83e5-f64c1eeb165e

I can't delete it whether I select it or press backspace.

Moreover, I found a new bug. If two notes with the same title are selected for export at the same time, only one file will be exported and the other file will be overwritten. Can you add an option to save two files without changing the title?

In addition, if I can, I want a function that can merge notes. This function can combine the contents of two notes to generate a new note, so that it has the contents of the original two notes.

**Comment by WaterTreee** [comment]
Supplement the functions mentioned above: As mentioned above, the contents of two notes can be merged into a new note, but not limited to two notes, and more notes can also be merged into one note.

The advantage of doing this is that you can integrate scattered ideas or inspirations in one place, instead of having to find notes on a specific topic to edit it every time you record inspiration.

Moreover, it is not only convenient for classification, but also convenient for reading. Although there is a label function, it is always a bit troublesome to open the notes one by one.

**Comment by PhilKes** [comment]
To keep things in order, please open a separate issue for the suggested merge notes feature.
For the bug with 2 notes with the same title being exported, I will fix this together with #143.

For your original bug of not being able to delete words, I cant reproduce this, you seem to be using some custom keyboard with Arrow-Keys(?). The best I could do is to select a word like you did in the Android Emulator via my computer keyboard (Shift + Left Arrow), but deleting the selected word via backspace works fine with that too:

[notallyx_issues_142_2.webm](https://github.com/user-attachments/assets/a11e2389-ae25-4cec-94cf-8ae86ca295ba)

**Comment by WaterTreee** [comment]
I see. 

For the problem that I can't delete words, you can try to switch to other language input to simulate it, such as Chinese input or pinyin input.

The following is the situation in Chinese input state:
https://github.com/user-attachments/assets/c2621ac3-b715-45d4-a9cf-d2f10bdacdce

---
In order to facilitate your debugging, I uploaded the input method application to the link. You can use them if you need them.

https://github.com/WaterTreee/Fortree/releases/download/keyboard/Gboard_v8a.zip

https://github.com/WaterTreee/Fortree/releases/download/keyboard/BaiduKeyboard_6.8.1.4.zip

**Comment by PhilKes** [comment]
Thanks for the additional info, I am pretty sure I found the problem. Somehow when using the chinese keyboard the `KeyEvent` handlers are called a bit differently. I opened a PR #155 which fixes this problem, I tested it with the chinese (pinyin) keyboard
