### ISSUE TITLE
RECORD_AUDIO permission

### ISSUE THREAD

**Issue by IzzySoft** [PhilKes/NotallyX#147]
Our scanners just sent in a warning:

    ! repo/com.philkes.notallyx_621.apk declares sensitive permission(s):
      android.permission.RECORD_AUDIO

Before I do "guesswork" (the Readme gives no clue), I assume there is some "audio notes" feature?

**Comment by PhilKes** [comment]
Yep you can record audio notes, dont know why the original author didn't include it in the `full_description` or `README`.
Added it in https://github.com/PhilKes/NotallyX/commit/df2cd719f2072fe38d55de7425cc47ebd6634b1a

**Comment by IzzySoft** [comment]
Thanks! Added to the app's "green list" so it gets transparently shown :smiley:
