### ISSUE TITLE
Improving Image Display on Notes

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/NotallyX#15]
Currently, adding more than two images doesn't display anything on the main screen; they only appear when you open the note. I recommand displaying a small text indicator on the main screen to show how many images are in the note.

**Comment by PhilKes** [comment]
@CodeNomadHQ Sorry about merging without waiting for feedback, I just waited to merge all PRs head on to be able to do the renaming of the project just now

If the PR does not satisfy what you wanted, you can reopen this issue

**Comment by CodeNomadHQ** [comment]
No worries, I understand! You've made a great step by adding this, and I appreciate it. I agree there’s room for improvement in the future. I’ll reopen this after we’ve fixed the other features. Thanks for your work on this!
