### ISSUE TITLE
Parse list items when pasting a list formatted text into a list note 

### ISSUE THREAD

**Issue by Ultrabenosaurus** [PhilKes/NotallyX#150]
### What happened?

I'm trying to migrate my notes from the Zoho app, but I'm stumped with my groceries list. When I paste it into a new "list" it's all just one item, and my keyboard is showing a "next" key instead of enter/return so I can't split it up.

I have pasted the list into a text note, deleted the line breaks and hit enter again with the hope NotallyX's own formatting would be copy-pasteable into a "list" but this also doesn't work. 

I have also exported the list to plain text and imported it into NotallyX but oy imports as a text note and I cannot see any way to convert it. 

As things stand, my only option seems to be typing out everything again manually? 

![Screenshot_20241207-073240](https://github.com/user-attachments/assets/c3d9d7c9-43d7-4bda-b81f-c80a8809a336)

### App Version

6.2.1

### Android Version

13

**Comment by PhilKes** [comment]
Not a bug, just a missing feature. But I agree it should be possible to paste a list directly into a List note and have the lines being parsed into separate items.
Currently if you paste a text into a list note it doesnt check for any sort of list syntax, just pastes the plain text.

Currently when importing a plain text file it checks if the file's contents start with any of the following list syntaxes:

- Markdown: "- [ ]" or "- [x]"/"- [X]"
- NotallyX internal: "[ ]" or "[✓]

I will add the following syntaxes as well:
- plain newlines, like:
  ```
  Item1
  Item2
  Item3
  ```
 - "-" or "*":
   ```
   - Item1
   - Item2
   - Item3
   ```
   ```
   * Item1
   * Item2
   * Item3
   ```
 And I will also make sure that these syntaxes are also checked if you paste text into a list note.
 With this you should be able to paste your example into a list note and get the separate list items.

**Comment by Ultrabenosaurus** [comment]
Amazing! Thank you for the quick response and implementation!
