### ISSUE TITLE
Paste text containing link does not convert to clickable link + polish translation

### ISSUE THREAD

**Issue by rafnov** [PhilKes/NotallyX#157]
Both visible on 1 screenshot.

1st is rather "cosmetic" but easily visible from 1st run. It is about translation in my language not full. I mean "Created" word. This issue is present since I installed NotallyX 1st time, which was like few versions before. Created is: "utworzono" with neuter gender and "utworzona" with female gender, like word "note" (notatka) is in both english and polish.

2nd is about links not "clickable".
I just can't open browser, by tapping the link because it's treated as text, not the link. It would be great to have the possibility to tap the link to automatically open browser.

Thx for your work and good luck with your application to Google Play. Btw. Any news about that?

![Screenshot_2024-12-11-15-04-07-15_e75fb415cadfe02fd201d2336c965d41.jpg](https://github.com/user-attachments/assets/1d38426e-7b6f-44b2-b36a-a8a69d03ce61)

**Comment by PhilKes** [comment]
I will add the polish translation for created.
Btw there are many more missing polish translations, if you want I can provide you with an excel sheet, if you want to have a complete polish translation in the app.

About the links not clickable, they are clickable when you open the note. In the overview its always just text, not clickable. In Google Keep it behaves the same way. I dont know if its a good idea to make every link clickable from the overview, since it can interfere with opening notes or scrolling.

The Google Play internal test has 1 more day to go, after that I can apply again for production, we'll see if it works out better this time 🙃

**Comment by rafnov** [comment]
Unfortunately links are not clickable here after displaying the note.
You see the coursor vertical on the text. They are not even marked as a links with usual underline or changing color, like other apps do.

![Screenshot_2024-12-13-07-45-52-15_e75fb415cadfe02fd201d2336c965d41.jpg](https://github.com/user-attachments/assets/e9f4ee84-ff24-4027-a896-cd85809404ee)

**Comment by PhilKes** [comment]
How did you add the links?

If you paste a link it is automatically converted into a clickable link:

[notallyx_issues_157_paste_link.webm](https://github.com/user-attachments/assets/2c2c8637-b061-40c8-841b-d60db3c02906)

You can also manually mark text as a link via the "Link" option:

[notallyx_issues_157_link.webm](https://github.com/user-attachments/assets/13c66626-d189-43c5-953b-3a1326c8302d)

**Comment by rafnov** [comment]
Ok, I understood what happened.
I've pasted large piece of the text with links inside and they were not converted. But shouldn't they be converted anyway?
Happily I can double tap the text link, that is not converted and the option to open (otwórz) appears.

![Screenshot_2024-12-23-01-52-35-85_e75fb415cadfe02fd201d2336c965d41.jpg](https://github.com/user-attachments/assets/b9249221-c2c8-4560-9b28-66a77437cb85)

Links pasted alone to the text are converted indeed.

**Comment by PhilKes** [comment]
Now I understand, indeed currently a pasted link is only correctly converted to a clickable link if the entire pasted text is a link.
I will implement that it looks inside of the pasted text for links separately instead.
