### ISSUE TITLE
Improve app theme's color contrasts 

### ISSUE THREAD

**Issue by volker001** [PhilKes/NotallyX#163]
The font color of the links is not easy to read and too pale in relation to the normal text. The link colors and the color of the normal text should be more balanced for good reading.

**Comment by PhilKes** [comment]
I agree, since #104 some of the original theming does not work as well anymore.
I am thinking about doing a fresh Material 3 Theme instead of trying to keep faith to the old Material 2 theme as I tried before in order to get a more consistent and user-friendly look of the app
