### ISSUE TITLE
Scrollbar missing ...

### ISSUE THREAD

**Issue by volker001** [PhilKes/NotallyX#178]
### What happened?

Scroll Bar is missing for longer texts. The text disappears behind the keyboard layout and does not appear to edit visibly.

### App Version

6.3.0

### Android Version

13

### (Optional) Relevant log output

Hmm, now it works again.
Don't know what's going wrong...

**Comment by amadoumx** [comment]
I have the same issue:

App Version

6.3.0

Android Version

13
