### ISSUE TITLE
More options for sorting Notes in Overview

### ISSUE THREAD

**Issue by PhilKes** [PhilKes/NotallyX#29]
I had a look at some Google Play Store reviews for Notally, and this was mentioned multiple times.

It should be possible to manually sort the notes in the overview, not just statically by their creation date.
I also saw some requests for sorting after modified date, instead of created date

Proposal:
* Add new preference `Notes sort order` with options:
   * By creation date
   * By modified date (have to add modified date as a column to database)
   * Manual order:
       - Perhaps adding `order` column in `BaseNote` table
       - Re-ordering of notes via drag'n'drop
       
Since the manual order takes much more effort, this could be split into another issue

**Comment by ippocratis** [comment]
Another common sorting option is "by name" 

Maybe "by type" also makes sense by means of notes that are "to-do" ,plain text,containing images,containing files ....
