### ISSUE TITLE
Linking Notes Within Notes 

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/NotallyX#32]
This idea has been on my mind for a while, and allowing linking notes within other notes would work the same as linking a website, but here, you’re linking to another note

**Comment by PhilKes** [comment]
Good idea, I am just not sure yet how exactly, as a user would you want to do that?
Implement it something like linking issues/PRs here in Github, where you type '#' and then a popup shows you the available issues/PRs to link?

![image](https://github.com/user-attachments/assets/5db2df7e-f878-4862-9387-10267ff7bc81)

Or do you want to add it in the toolbar and a popup allows you to select which note to link to?

**Comment by CodeNomadHQ** [comment]
I think when you click the link option in the toolbar, it should show two options: one for linking a website and another for linking a note. If you choose to link a note, a popup would appear where you can select the note.

**Comment by PhilKes** [comment]
> I think when you click the link option in the toolbar, it should show two options: one for linking a website and another for linking a note. If you choose to link a note, a popup would appear where you can select the note.

Sounds like a plan. I havent use the "Link" feature much yet, but I find it very unintuitive that you have to paste a URL, then select it and press "Link" to make it a clickable link. I think I will add that if you paste a text it will check if it is a URL and if yes, then it will wrap it in a URL span to make it clickable right away.
