### ISSUE TITLE
App crashes when pin lock is enabled

### ISSUE THREAD

**Issue by ippocratis** [PhilKes/NotallyX#50]
![logcat_10-20-2024_16-12-59.txt](https://github.com/user-attachments/files/17450360/logcat_10-20-2024_16-12-59.txt)

Attached logs 

Running on android 14

**Comment by PhilKes** [comment]
Sorry I forgot to test the released APK on my phone separately.
I needed to add SQLCipher to the `proguard-rules` 
I have updated the APK, please try again with https://github.com/PhilKes/NotallyX/releases/download/v6.0-RC3/NotallyX-6.0-RC3.apk

**Comment by ippocratis** [comment]
> I have updated the APK, please try again 

Fixed
