### ISSUE TITLE
Show Last Modified Dates in Notes

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/NotallyX#60]
**Describe the solution you'd like**
When sorting notes by the last modified date, the notes are reordered correctly, but the last modified date isn’t displayed within the notes themselves. It would be clearer if the last modified dates were shown instead of random dates.

**Showcase**

<img width="501" alt="image" src="https://github.com/user-attachments/assets/31066717-214d-4ce0-974e-b9496f28e0f2">

**Comment by PhilKes** [comment]
Perhaps we should remove the `Date Format` preference all together. Instead, if you sort by last modified date you will see e.g. "Modified x Minutes ago", or if you sort by created date `Created x Minutes ago`, if you sort by title there wont be any date displayed.

For the Widget I personally always want to hide the date, I dont see any benefit, it just takes up space.

What do you think?

**Comment by CodeNomadHQ** [comment]
> Perhaps we should remove the Date Format preference all together. Instead, if you sort by last modified date you will see e.g. "Modified x Minutes ago", or if you sort by created date Created x Minutes ago, if you sort by title there wont be any date displayed.

I have mixed feelings about it. Part of me thinks we should keep both created and modified dates in the note but in different location. On the other hand, I like your idea as well.


> For the Widget I personally always want to hide the date, I dont see any benefit, it just takes up space.

 I totally agree

**Comment by PhilKes** [comment]
> > Perhaps we should remove the Date Format preference all together. Instead, if you sort by last modified date you will see e.g. "Modified x Minutes ago", or if you sort by created date Created x Minutes ago, if you sort by title there wont be any date displayed.
> 
> I have mixed feelings about it. Part of me thinks we should keep both created and modified dates in the note but in different location. On the other hand, I like your idea as well.
> 
> > For the Widget I personally always want to hide the date, I dont see any benefit, it just takes up space.
> 
> I totally agree

I just think if someone sets sort by modified date in the preference, why would they want to see the created date? That would just be confusing. Same if you sort by creation date but display the modified date.

Btw. I also noticed that in the Activity to select a Note to display on the Widget the sort by preference is not used, it just shows the notes in "random" order. I guess we should align this too.

**Comment by CodeNomadHQ** [comment]
Yeah, I agree, let's do it that way!
