### ISSUE TITLE
Add more Export formats

### ISSUE THREAD

**Issue by PhilKes** [PhilKes/NotallyX#62]
**Describe the solution you'd like**
Currently you can only export as a `.zip` which includes the SQLite Database + files.
It would be nice to have other options for more useful formats like TXT, JSON, PDF or HTML

**Additional context**
https://github.com/OmGodse/Notally/pull/148

TODOs:
- [x] Export Notes to TXT files (1 Note = 1 `txt` file)
- [x] Export Notes to JSON (1 `json` file with an array of `BaseNote` json representations)

**Comment by HazyDuck** [comment]
I would like to add to this, exporting encrypted notes

**Comment by ippocratis** [comment]
> I would like to add to this, exporting encrypted notes

The export zip is already encrypted on V6

**Comment by HazyDuck** [comment]
> > I would like to add to this, exporting encrypted notes
> 
> The export zip is already encrypted on V6

I see, iwasn't aware, thanks for the information.

**Comment by ippocratis** [comment]
> Are you sure? I can see the zip data in file explorer. 
Sorry bad selection of words.
It will be available when V6 is available in releases .
Commits are merged to main.
https://github.com/PhilKes/NotallyX/pull/56

**Comment by PhilKes** [comment]
> > > I would like to add to this, exporting encrypted notes
> > 
> > 
> > The export zip is already encrypted on V6
> 
> Are you sure? I can see the zip data in file explorer.

To clarify this, if you use `v6.0` and have a backup password setup, the exported `.zip` are indeed encrypted, **but** you can still look into the `.zip` file without the password, but you cant open/extract any file in the zip archive without entering the correct password. That is by design, for more infos see this comment from the author of `zipf4j` https://github.com/srikanth-lingala/zip4j/issues/113#issuecomment-560584399

**Comment by HazyDuck** [comment]
> > > > I would like to add to this, exporting encrypted notes
> > > 
> > > 
> > > The export zip is already encrypted on V6
> > 
> > 
> > Are you sure? I can see the zip data in file explorer.
> 
> To clarify this, if you use `v6.0` and have a backup password setup, the exported `.zip` are indeed encrypted, **but** you can still look into the `.zip` file without the password, but you cant open/extract any file in the zip archive without entering the correct password. That is by design, for more infos see this comment from the author of `zip4j` [srikanth-lingala/zip4j#113 (comment)](https://github.com/srikanth-lingala/zip4j/issues/113#issuecomment-560584399)

I'm currently using v6.0 but I do not see a backup password option. 

![Screenshot_20241028-104345](https://github.com/user-attachments/assets/ff22ed5b-78e7-48bf-9b3a-d97a49b2f93d)

**Comment by PhilKes** [comment]
> > > > > I would like to add to this, exporting encrypted notes
> > > > 
> > > > 
> > > > The export zip is already encrypted on V6
> > > 
> > > 
> > > Are you sure? I can see the zip data in file explorer.
> > 
> > 
> > To clarify this, if you use `v6.0` and have a backup password setup, the exported `.zip` are indeed encrypted, **but** you can still look into the `.zip` file without the password, but you cant open/extract any file in the zip archive without entering the correct password. That is by design, for more infos see this comment from the author of `zip4j` [srikanth-lingala/zip4j#113 (comment)](https://github.com/srikanth-lingala/zip4j/issues/113#issuecomment-560584399)
> 
> I'm currently using v6.0 but I do not see a backup password option.

Oh I'm sorry I confused some Github issues here, the backup password was implemented in
https://github.com/PhilKes/NotallyX/issues/18

Which is not included in `v6.0`, it will be in `v6.1` (I always use Github tags to show in which release the feature will be).
But I will release a `v6.1-RC1` in the coming days, so you can test the backup password setting then.
Sorry for the inconvenience

**Comment by PhilKes** [comment]
> I'm currently using v6.0 but I do not see a backup password option.

FYI I just released a alpha version, which includes the backup password option
https://github.com/PhilKes/NotallyX/releases/tag/v6.1-RC1

**Comment by HazyDuck** [comment]
> > I'm currently using v6.0 but I do not see a backup password option.
> 
> FYI I just released a alpha version, which includes the backup password option https://github.com/PhilKes/NotallyX/releases/tag/v6.1-RC1

Amazing thank you, works great.
