### ISSUE TITLE
Ability to swipe ListItem on DragHandle

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/NotallyX#67]
### What happened?

Dragging a task with the mouse is not functioning properly.

### Showcase

https://github.com/user-attachments/assets/9cfc64dd-fae6-4545-9213-4a2460e12f9c

### App Version

6.0

### Android Version

15

**Comment by PhilKes** [comment]
The DragHandle icon is currently only used to drag an item up/down, you can not swipe on it.
But I agree it would be intuitive to be able to swipe with it as well as drag up/down. That would be the same behaviour as in Google Keep
