### ISSUE TITLE
Creating categories

### ISSUE THREAD

**Issue by Uranusek** [PhilKes/NotallyX#72]
**Describe the solution you'd like**
Could you add an option to create categories so I can later move tasks, shopping lists, etc. to them? Currently I have to use archive and trash for this. 

**Additional context**
This would help keep things organized. I think it would be best to do it in the side panel.

**Comment by PhilKes** [comment]
You can create `Labels` and tag notes with it. You can then navigate to see all notes of a `Label` via the `Labels` navigation option

[notallyx_issues_72.webm](https://github.com/user-attachments/assets/e78ea31e-d6be-4c23-9967-f86c1690dbb8)

There are some open issues to improve the `Labels` feature:
https://github.com/PhilKes/NotallyX/issues/78
https://github.com/PhilKes/NotallyX/issues/49

**Comment by Uranusek** [comment]
I know, but I also use labels to create task descriptions. As a result, there are a lot of them and it becomes a mess. Creating categories would be more convenient, e.g. I create a "tasks" category and move the task lists there. This would help me organize my notes, tasks and shopping lists instead of keeping everything in notes. 

Actually, #49 could be a solution if I could select which labels to display instead of displaying all of them.

**Comment by PhilKes** [comment]
> I know, but I also use labels to create task descriptions. As a result, there are a lot of them and it becomes a mess. Creating categories would be more convenient, e.g. I create a "tasks" category and move the task lists there. This would help me organize my notes, tasks and shopping lists instead of keeping everything in notes.
> 
> Actually, #49 could be a solution if I could select which labels to display instead of displaying all of them.

Yes I think #49 will solve your problem. I want to align the `Labels` feature as much to Google Keeps implementation as possible, since I think its the most intuitive

**Comment by PhilKes** [comment]
@Uranusek can you check if https://github.com/PhilKes/NotallyX/pull/99 satisfies your needs?

**Comment by Uranusek** [comment]
Yes, if I could choose which labels to display.

**Comment by PhilKes** [comment]
> Yes, if I could choose which labels to display.

If you click on a label you will see all notes that have that label

**Comment by Uranusek** [comment]
I know, but what I want is the ability to choose which labels are displayed in the side panel. If they are displayed alphabetically, it won't solve my problem. 

It would be best to be able to create categories (folders) and move whatever you want there. Labels don't make this possible.

**Comment by PhilKes** [comment]
Hm to be honest I dont see the difference between a folder and a label, if you just want to hide some labels in the side panel we could implement that in the `Labels` View where every label is listed there is a hide/show button which toggles if the label is visible in the side drawer.

**Comment by PhilKes** [comment]
@Uranusek how about this:

[notallyx_issues_72_2.webm](https://github.com/user-attachments/assets/d9bef302-0477-4c46-80b7-58283fc5f194)

**Comment by Uranusek** [comment]
>how about this:

That's exactly what I meant. But I think the icons should be reversed. Crossed out should indicate a hidden label. 

>Hm to be honest I dont see the difference between a folder and a label

Folders would behave like archive and trash. I could move whatever I want there. Labels only allow display something, but everything is still in the notes folder.

**Comment by PhilKes** [comment]
> > how about this:
> 
> That's exactly what I meant. But I think the icons should be reversed. Crossed out should indicate a hidden label.
> 
> > Hm to be honest I dont see the difference between a folder and a label
> 
> Folders would behave like archive and trash. I could move whatever I want there. Labels only allow display something, but everything is still in the notes folder.

I would just prefer to not add another hierarchy layer since it can become quite cumbersome fast, especially in a mobile app.
So I hope that #107 is sufficient
