### ISSUE TITLE
Pin/label multiple Notes

### ISSUE THREAD

**Issue by PhilKes** [PhilKes/NotallyX#78]
**Describe the solution you'd like**
Currently if you want to add multiple notes to the same `Label` or pin them you have to select them one by one and add them to the `Label`/pin.
There should be an option in the top toolbar to add all selected Notes to a `Label`/pin them

![image](https://github.com/user-attachments/assets/60bea3bd-c511-49d2-8580-f101e85bdee2)

**Comment by ippocratis** [comment]
Very useful
