### ISSUE TITLE
Auto Discard Empty Notes

### ISSUE THREAD

**Issue by Dragonfly-30** [PhilKes/NotallyX#86]
By default, Notally does not auto delete the Empty notes which has to be done by us manually. Auto deleting empty notes can be nice QOL feature.

By Empty Notes, I mean the notes that neither have a title nor a body.

**Comment by ippocratis** [comment]
empty notes are not auto deletwd in 6.1 rc1

**Comment by PhilKes** [comment]
> empty notes are not auto deleted in 6.1 rc1

The changes were made after the rc1
You can see all changes that have been merged but are not in rc1 here: https://github.com/PhilKes/NotallyX/compare/v6.1-RC1...main

But I will release a rc2 tomorrow I think. I would have already released v6.1 already but I wanted to complete the F-Droid release stuff first, so I can now just easily release new version there too
