### ISSUE TITLE
Color the navigation bar

### ISSUE THREAD

**Issue by Uranusek** [PhilKes/NotallyX#95]
**Describe the solution you'd like**
The navigation bar is gray, even for the light theme. It should be white/dark gray to match the background color. 

**Additional context**
None.

**Comment by PhilKes** [comment]
I am not really sure what you are referring to:

<div style="display: flex; justify-content: space-between; width: 100%;">
<img src="https://github.com/user-attachments/assets/e6dfe441-f876-499b-b2a6-127c00963c0d" width="250"/>
<img src="https://github.com/user-attachments/assets/417ee72d-5d0d-45f1-aabb-69492cb78c87" width="250" />
</div>

**Comment by PhilKes** [comment]
> Yep, with the one on the top everything is fine, only the bottom one does not change color.

Ok now I understand, the thing is in the android emulator (see my screenshots) the standard Android navigation bar is hidden, thats why I wasnt sure what you meant. But changing the android navbar color is no problem, will fix it
